<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Shape renderer</title>
    <link rel="stylesheet" href="public/assets/css/style.css">
    <script
        src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
</head>
<body>
    <header></header>
    <main>
        <div class="message"></div>
        <svg>
            <?php 
            
                $triangle->draw();
            
            
            $elipse->draw();
            $circle->draw();            
            ?>

        </svg>
        <div>
            <button id="triangle">Triangle</button>
            <button id="elipse">Elipse</button>
            <button id="circle">Circle</button>
        </div>
    </main>
    <footer></footer>
    <script src="public/assets/js/main.js"></script>
</body>
</html>